-- откат схемы (DOWN)

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS risk_limits;
DROP TABLE IF EXISTS opportunities;
DROP TABLE IF EXISTS trades;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS bots;
DROP TABLE IF EXISTS fx_rates;
DROP TABLE IF EXISTS fees;
DROP TABLE IF EXISTS markets;
